version: '3.8'

services:
  nginx-waf:
    image: owasp/modsecurity-crs:nginx-alpine  
    ports:
      - "8000:8000"
      - "8001:8001"
      - "4430:4430"
    environment:
      BACKEND_1: "http://juice_shop_1:3000"  
      BACKEND_2: "http://juice_shop_2:3000"  
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf  # Кастомная конфигурация NGINX
    depends_on:
      - juice_shop_1
      - juice_shop_2
    networks:
      - app_network

  juice_shop_1:
    image: bkimminich/juice-shop 
    networks:
      - app_network

  juice_shop_2:
    image: bkimminich/juice-shop 
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
